### PR TITLE
MacOS support

### PR DESCRIPTION
**Pull request by Frost-54**
Added support for MacOS 10.5+

### CODE REVIEW

**Comment by ThomasMonkman** [comment]
Thank you very much for this pr, it must have been a lot of work.
Apologise for the delay, I don't have a mac, and had to wait for someone to test for me.

I'm going to accept the pr, but I do have some questions.

in windows version of
`absolute_path_of`

is it not possible to use the way its currently done on master for `GetFileAttributesA/W` where its just two templated functions overloaded on `char` and `wchar_t`, is there a need to use constexpr and create your `IsWChar` template stuff?

Further for `walkDirectory` in the mac side of things
you have the below.
Why is this needed? there is no other version of this function
`template<typename Fn, class = std::enable_if<Invokable<Fn, StringType>::value>>`

So if this is false and that template is not compiled, what takes it place? or is the code not used further up the chain?

**Comment by pinguin999** [comment]
Thanks, it's working fine. But I get this warning:

`warning: 'FSEventStreamScheduleWithRunLoop' is deprecated: first deprecated in macOS 13.0 - Use FSEventStreamSetDispatchQueue instead. [-Wdeprecated-declarations]`

Can we update the code to use FSEventStreamSetDispatchQueue?

Using this code works at least for my use case.

```
    dispatch_queue_t fsevents_queue = nullptr;
    fsevents_queue = dispatch_queue_create("fswatch_event_queue", NULL);
    _run_loop = CFRunLoopGetCurrent();
    FSEventStreamSetDispatchQueue(_directory, fsevents_queue);
```

**Comment by Frost-54** [comment]
Thanks for the review!

1. Yes, it's possible. (Edit: if you want to pass the string as a pointer)
2. Adding the 'enable_if' is just for diagnostics purpose. Feel free to remove it.
3. I haven’t update to MacOS 13 when I wrote the code. Also, it crashed in CFRunLoopStop when cleaning up on my machine. dispatch_queue maintains a pool of threads internally, so the optimal solution is not as simple as changing a function call.

Stack trace when running the test:

==58326==ERROR: AddressSanitizer: SEGV on unknown address 0x0001027f0334 (pc 0x0001a1718590 bp 0x00016d6f0b30 sp 0x00016d6f0b20 T0)
==58326==The signal is caused by a UNKNOWN memory access.

    #0 0x1a1718590 in CFRunLoopStop+0x5c (CoreFoundation:arm64e+0xb1590)
    #1 0x1029386c4 in filewatch::FileWatch<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::destroy() FileWatch.hpp:374
    #2 0x1029383b8 in filewatch::FileWatch<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::~FileWatch() FileWatch.hpp:194
    #3 0x1028a989c in filewatch::FileWatch<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::~FileWatch() FileWatch.hpp:193

**Comment by pinguin999** [comment]
After updating to FSEventStreamSetDispatchQueue, I was able to remove _run_loop from the project.

But I have no idea what I'm doing ^^

```
void monitor_directory()
{
      dispatch_queue_t fsevents_queue = nullptr;
      fsevents_queue = dispatch_queue_create("fswatch_event_queue", NULL);
      FSEventStreamSetDispatchQueue(_directory,
                                    fsevents_queue);
      FSEventStreamStart(_directory);
      _running.set_value();
      CFRunLoopRun();
}
```

**Comment by pinguin999** [comment]
Also I have this error with my tests.

```
error: comparison of unsigned expression in '>= 0' is always true [-Werror=type-limits]
    for (size_t i = len - 1; i >= 0; i--) {
```

**Comment by Frost-54** [comment]
@pinguin999 Yes, _run_loop is no longer needed. You can also removing the callback thread and event monitoring thread. See my newest pr for the changes.

**Review by Theghost256 — APPROVED** [review]

**Pull request merged**
